# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: medcom.fhir.dk.terminology
canonical: http://medcomfhir.dk/ig/terminology
name: MedComTerminology
title: "DK MedCom Terminology"
description: The DK MedCom Terminology IG
status: active # draft | active | retired | unknown
version: 1.4.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: Release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://www.medcom.dk

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true

menu:
  Home: index.html
  Terminology: terminology.html
  Artifacts: artifacts.html
  Downloads: downloads.html

